language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25

script:
  - ./gradlew build
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport
