language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - pip install --user codecov

script:
  - ./gradlew build
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport
  - codecov
